### ISSUE TITLE
Homey crash when enabling V2.0 beta

### ISSUE THREAD

**Issue by Asinke** [gruijter/com.gruijter.insights2csv#1]
Hi Robin, While testing your app I noticed homey crashes (tested twice, crashed twice). 
How can I help you providing required information?

**Comment by gruijter** [comment]
This is caused by a bug in Homey Insights itself. It is a long lasting bug, and we can only hope Athom has it fixed in v2.

**Comment by gruijter** [comment]
I'm rewriting the app to be compatible with Homey V2. The insights handling has been significantly changed.
