### ISSUE TITLE
Export Insights to Onedrive 

### ISSUE THREAD

**Issue by pngoosen** [gruijter/com.gruijter.insights2csv#11]
Can you please give me a clue what parameters I have to use when I want to export Homey Insights to a folder in my Onedrive. As far as I know, Onedrive is Webdav compatible!?

**Comment by gruijter** [comment]
Dunno. Havent used onedrive myself for this. A google gave me this link though:

https://winscp.net/eng/docs/guide_microsoft_onedrive

You could try the forum for further help.

**Comment by antonhagg** [comment]
@pngoosen did you mange to find out about this? I'm trying the same but ending up with 401 error.
