### ISSUE TITLE
FTP bug

### ISSUE THREAD

**Issue by horakmartin** [gruijter/com.gruijter.insights2csv#28]
Hello, from last update I have problem with my FTP connection. Test is OK but after export, there is a error log.

[log] 2022-06-01 06:26:53 TypeError: this.FTPClient.on is not a function at App.getFTPClient (/app.js:729:19) at App.saveFTP (/app.js:750:15) at App._exportApp (/app.js:880:16) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async App.runQueue (/app.js:225:4)
[log] 2022-06-01 06:26:53 error: TypeError: this.FTPClient.on is not a function at App.getFTPClient (/app.js:729:19) at App.saveFTP (/app.js:750:15) at App._exportApp (/app.js:880:16) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async App.runQueue (/app.js:225:4)
[log] 2022-06-01 06:26:53 26 files zipped, 126202 total bytes

**Comment by gruijter** [comment]
Fixed now. Thx for reporting!
