### ISSUE TITLE
Problems with subdirs in NAS settings.

### ISSUE THREAD

**Issue by henkbart** [gruijter/com.gruijter.insights2csv#5]
Hallo Robin,

I first tried only NAS (SMB)
There i found that i only have access to te root dir of my share. Not to the subdirs.
The user has admin rights so that is not the problem.

The full path is //ip address/Drivename/subdir name

When using that i got an error that he can not find the share.

I then switched to FTP. That is allowing subdirs.
But when executing a flow, nothing is going to the dir.......

Then i used both (NAS and FTP)
Then the FTP is working en storing it in the subdir i wanted.
The NAS is stil only storing it in the root...

Henk

**Comment by gruijter** [comment]
![2019-08-25 (1)](https://user-images.githubusercontent.com/19174120/63643216-eee29c00-c6cb-11e9-9731-ff8b08b86292.png)

I just uploaded v2.4.2 to the appstore. It adds the possibility to specify a subfolder on your network share for SMB (NAS)
