### ISSUE TITLE
Managerlnsights is not ready

### ISSUE THREAD

**Issue by MrDayOff** [gruijter/com.gruijter.insights2csv#9]
Not sure if it's something to do with you app, i get this message:

> 
Managerlnsights is not ready because it did not initialize properly. Error message: Unable to connect to rrdcached: No such file or directory 
> 

8fbf5a0b-edab-43fc-bf5f-c1b83e07a0d1

**Comment by gruijter** [comment]
When do you get this message? When doing an export? Did you try to do a ptp of Homey?

**Comment by MrDayOff** [comment]
Hi,

I get this when i go to https://insights.homey.app/
Probably same error comes when i use the backup tool. I saw that there is
an update comming (now beta) for Homey that maybe fixes this issue. So lets
wait first.

Barry

Op zo 22 mrt. 2020 12:27 schreef gruijter <notifications@github.com>:

**Comment by gruijter** [comment]
Please try the new version 3:
https://homey.app/en-gb/app/com.gruijter.insights2csv/Archive-Insights/test/

Reopen the issue if you still have this problem
